upstream server {
    server authapp:7000;
}
upstream server2 {
    server experimentapp:8000;
}
upstream server3 {
    server feedbackapp:9000;
}
upstream server4 {
    server pythonapp:6000;
}

server {
    listen 80;
    
    location /authapp {
        rewrite ^/authapp/(.*) /$1 break;
        proxy_set_header Host $host;
        proxy_pass http://server;
    }
    location /experimentapp {
        rewrite ^/experimentapp/(.*) /$1 break;
        proxy_set_header Host $host;
        proxy_pass http://server2;
     }
    location /feedbackapp {
        rewrite ^/feedbackapp/(.*) /$1 break;
        proxy_set_header Host $host;
        proxy_pass http://server3;
     }
    location /pythonapp {
        rewrite ^/pythonapp/(.*) /$1 break;
        proxy_set_header Host $host;
        proxy_pass http://server4;
     }
}